[[pages]]
path = "pages/all_mutual_funds.py"
name = "All Mutual Funds"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/watchlist.py"
name = "Watchlist"
icon = "ğŸ‘€"

[[pages]]
path = "pages/mf_details.py"
name = "Mutual Fund Details"
icon = "ğŸ“"


[[pages]]
name = "Simulations"
icon = "ğŸ¯"
is_section = true

[[pages]]
path = "pages/simulations/simulate_strategy.py"
name = "Simulate Strategy"
icon = "âš¡"

[[pages]]
path = "pages/simulations/saved_simulations.py"
name = "Saved Simulations"
icon = "ğŸ’¾"


[[pages]]
name = "Investments"
icon = "ğŸ’°"
is_section = true

[[pages]]
path = "pages/investments/add_or_delete_investment.py"
name = "Add/Delete Investment"
icon = "â•"

[[pages]]
path = "pages/investments/my_investments.py"
name = "My Investments"
icon = "ğŸ“‚"


